### ISSUE TITLE
web: processor: add kill participation

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/meta#13]
* [x] add to `web.participant`
  * [x] calculate in `processor.queries.participant`
  * [x] migrate existing participants

**Comment by kvahuja** [comment]
Query on existing table
```
ALTER TABLE PARTICIPANT_STATS
add column kda float,
add column kill_participation float;
```

but we can use migration to set the table up

**Comment by kvahuja** [comment]
also you can run migration to set the table up

**Comment by schneefux** [comment]
done
