### ISSUE TITLE
Web: The Home Page contrast needs to be revisited. The current combination of Green and all is not looking that well

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/meta#34]

**Comment by kvahuja** [comment]
@schneefux i used black and gray now. can you see if this makes sense? also i think we need a server to test on mobile. i use chrome for responsive and it's not effective. having said that i dont think i can buy 4 phones. i can test on ipad & iphone 6s & 7 plus

**Comment by kvahuja** [comment]
will close if @schneefux says colors look okay

**Comment by schneefux** [comment]
lgtm
