### ISSUE TITLE
web: processor: turret kills is showing 0 on web becase it's not getting inserted properly by processor

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/meta#44]
The API return ""turretCaptures": 4," but we are using 
```
COALESCE(NULLIF(participant->'data'->'attributes'->'stats'->>'turretKills', ''), '0')::int AS "turret_kills",
```

P.s.: dont want to rename column in web (ideally we should)

**Comment by kvahuja** [comment]
@schneefux please review SQL. also can we get data for older records?

**Comment by schneefux** [comment]
approved

No, it's lost unless we re-pull.
