### ISSUE TITLE
web: show a player's performance score

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/meta#47]
#23 and a PR also open

**Comment by kvahuja** [comment]
based on initial analysis...
---
1. http://vainsocial.dev/matches/744acd5c-07a9-11e7-aee5-02890c262897 -> all 3 cant be same. I recall SAW struggling and while Grumpjaw played an amazig captain with Petal just killing.
2. http://vainsocial.dev/matches/01eaa278-0817-11e7-aee5-02890c262897 -> looks almost right. however, if you see skill Tiers i think Krestel was highest of all and she could not kite Krul. she should be like a -1000. she was the reason why we lost.
3. http://vainsocial.dev/matches/cc674f6e-076e-11e7-aee5-02890c262897. it seems like Adagio carried but is still only Good. I am trying to recall this match and I recall GJ was always going after BF and BF after being spit out would just use his C and run away. Our Ringo was BS almost all game until he won a 1v1 againt Ringo (god knows how) and that was pretty much the end of it because.

overall i think the model is looks good.  we have to look at 
1. labels and being consistent - maybe names are just based on individual scores or relative? 
2. also we have to see why are some people just rated exactly same when they have very different scores. 
3. lastly, are these scores based on this 1 match analysis or does it account for anything across. so like if we were to re-train our DNN every weekend, will this change?  - if we can do this that will be most interested to go back and see what chnaged? and thats somethign we should record

**Comment by kvahuja** [comment]
@schneefux need query (can we even get one) to update ratings for older matches?

**Comment by kvahuja** [comment]
also on match #1, if we factor in SAW and what he's known for, player 3 wont have 99%. he got like 73 CS in a 15 min game which is so not saw. so if you think he failed. thats something we have to put in at some point in time.

**Comment by schneefux** [comment]
Possible, but could create some load. You need to open jobs for every participant api_id
```json
type = process
payload = {
type = participant
id = participant.api_id
}
```
I can build an SQL query for it. There is a Python script in analyzer (cli.py) that I use on local to run analyzer on one player.

**Comment by kvahuja** [comment]
query is fine to insert jobs, we will need it for production run. whats the query you been using locally? i will test it on my local.

**Comment by kvahuja** [comment]
we are now showing the same. we just need to see how good it is.

close this for now? @schneefux
