### ISSUE TITLE
processor: for 1 player the Lifetime data is wrong.

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/meta#52]
Search for 'sg/ImmortalDhruv' and then compare to 

https://api.dc01.gamelockerapp.com/shards/sg/players/?filter[playerNames]=ImmortalDhruv

total played should be 80, while DB only gets 21

**Comment by kvahuja** [comment]
data for me is also messed up (http://vainsocial.dev/players/sg/StormCallerSr)

**Comment by schneefux** [comment]
compiler was behind / crashed
