### ISSUE TITLE
improve home page search experience

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/meta#6]
Currently, a user
  * inserts their IGN
  * (presses enter and is confused)
  * selects the region
  * (is confused)
  * presses the search icon
  * is delayed or forwarded

I suggest changing the flow so that a user
  * inserts their IGN
  * presses a region button
  * is delayed or forwarded

which means removing the search icon and making the region buttons be more prominent.

**Comment by PierreAndreis** [comment]
http://pierreandreis.com/vainsocial/

**Comment by PierreAndreis** [comment]
https://github.com/PierreAndreis/vainsocial_home

**Comment by kvahuja** [comment]
thanks mate. will check it out today

**Comment by kvahuja** [comment]
@schneefux - is this better now after we have added the Serch button. The UI contrast issue is a new one #34

**Comment by schneefux** [comment]
I think we're good. If not, reopen.
