### ISSUE TITLE
discordbot: enable tracking

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/meta#75]

**Comment by schneefux** [comment]
Links now point to `/?src=discordbot`, `/players/eu/testplayer/?src=discordbot`, `/matches/matchid?src=discordbot`.
Waiting for web :)

**Comment by kvahuja** [comment]
sorry but can you use this format? Kinda standard

```
https://www.vainsocial.com/?utm_source=discordbot
```

I am trying to set this up on web.

**Comment by schneefux** [comment]
Sure. Is there a shorter version though? The bot prints the link, and with the tracking information it becomes twice as long.

**Comment by kvahuja** [comment]
so web is ready, just use the URL mentioned above. if you need a shorter version
```
https://goo.gl/2PAoXG
```

but remember this will always take you to a blank home page. if you want to link to a specific match page then just add the params

**Comment by schneefux** [comment]
added
