### ISSUE TITLE
processor: upsert data

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/meta#76]
In case we decide to force refresh from API, we need to update on conflict

**Comment by kvahuja** [comment]
is this for all objects? I believe player data is upserted already?

What's the best way to kick-off force-refresh? I want to put something on VS.com that allows people to do it themselves.

**Comment by schneefux** [comment]
Player data is upserted, conflicting other objects are dismissed.

I think that force refresh is a bad user experience. We should not need that.

**Comment by kvahuja** [comment]
so you saying if we need, we will push jobs from backend to force refresh everything? I still would like to see a way to do it - overall, maybe it's admin interface we use to insert such ops stuff.

I am thinking /admin (which is secured and all) our access to do any housekeeping stuff)

**Comment by kvahuja** [comment]
@schneefux is this required to be 1.2.0? are there any stats we need recalculation?

**Comment by schneefux** [comment]
Right now:
* Submit a job for MyIGN for Mo-Fr this week. apigrabber and processor insert all data.
* Submit the same job again. processor dismisses the data for non-player objects because objects with the IDs already exist.

Planned: 
...
* Submit the same job again. processor updates player objects and non-player objects.

Assuming the API data and processor queries never change, with the planned approach nothing happens.
In case API data changes or we change a query, with the planned approach we will update web tables, possibly inserting data that was previously missing.

It's 1.2.0, I just need to change a line or two.

**Comment by kvahuja** [comment]
ok cool

**Comment by schneefux** [comment]
fixed eb7bccc
