### ISSUE TITLE
web: Provide a way in DB to classify heros per their default role

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/meta#85]
On Branch 1.3.0, here are the steps:

```
select * from migrations where migration like ('%hero%')
```
> make sure you get 2 records for hero tables

```
delete from migrations where migration like ('%hero%')
```
> drop tables

```
php artisan migration
```
> setup hero tables

 Run this to seed data
> https://github.com/vainglorygame/vainsocial/commit/1bca0ca5c437208984f5d550cb87fdcf81356047

**Comment by kvahuja** [comment]
don't want to destabilise anything. will work on this today though.

**Comment by kvahuja** [comment]
@schneefux test and if works, please close it. 👍

**Comment by schneefux** [comment]
@kvahuja `participant.name` is like `*Glaive*` but `heros.name` is like `Glaive`, including famous `Sayoc`, `Hero019` etc.
I need mappings for them

**Comment by schneefux** [comment]
2c7d828
Rona is only mapped to `*Rona*`! Test and improve
